name: 'Dependency tree diff for Gradle'
description: "Dependency tree diff generates human readable dependency diff between 2 commits, using Jake Wharton's dependency-tree-diff tool"
inputs:
  baseref:
    description: 'Base ref'
    required: true
    default: ${{ github.base_ref }}
  headref:
    description: 'Head ref'
    required: true
    default: ${{ github.head_ref }}
  configuration:
    description: 'Selected configuration'
    required: false
    default: 'releaseRuntimeClasspath'
  project:
    description: 'Project'
    required: false
    default: 'app'
outputs:
  text-diff:
    description: "Dependency diff"
runs:
  using: 'docker'
  image: 'Dockerfile'
