on:
  pull_request:
  push:

jobs:
  test-job:
    runs-on: ubuntu-latest
    name: Run dependency diff action
    steps:
      - uses: actions/checkout@v2
      - id: dependency-diff
        uses: mateuszkwiecinski/dependency-tree-diff-action@master
      - run: echo random-number ${{ steps.dependency-diff.outputs.text-diff }}
        shell: bash
